### ISSUE TITLE
Attention Weights

### ISSUE THREAD

**Issue by pkhdipraja** [shahansa/mcan_attention_visualization#1]
Hello, I intend to use your implementation to get attention maps for the MCAN model. From which layer do you get the [image attention data](https://github.com/shahansa/mcan_attention_visualization/blob/cc225ee80346986c595a332179d47cbf443a777d/img_attn_visualization.py#L15) ? 

Thanks!

**Comment by shahansa** [comment]
Hi, 
It is rather straight forward, mentioned in section 4.3 of the mcan-vqa [paper](https://openaccess.thecvf.com/content_CVPR_2019/papers/Yu_Deep_Modular_Co-Attention_Networks_for_Visual_Question_Answering_CVPR_2019_paper.pdf)

**Comment by haoopan** [comment]
Can you share the detail to get the attention maps, how can we save the 'image_attn_val.pkl' file? Thank you very much !

**Comment by clytze0216** [comment]
> Can you share the detail to get the attention maps, how can we save the 'image_attn_val.pkl' file? Thank you very much !

Hi,@haopan
Did you find the ways to get the attention maps?if you succeed ,could you share the way to me?Thanks a lot !!
Looking forward to your reply~

**Comment by haoopan** [comment]
> > Can you share the detail to get the attention maps, how can we save the 'image_attn_val.pkl' file? Thank you very much !
> 
> Hi,@haopan
> Did you find the ways to get the attention maps?if you succeed ,could you share the way to me?Thanks a lot !!
> Looking forward to your reply~

Yes, just save the attention map(B, Num, HIDDEN_SIZE),  mentioned in section 4.3 of the mcan-vqa paper.

**Comment by clytze0216** [comment]
> > > Can you share the detail to get the attention maps, how can we save the 'image_attn_val.pkl' file? Thank you very much !
> > 
> > 
> > Hi,@haopan
> > Did you find the ways to get the attention maps?if you succeed ,could you share the way to me?Thanks a lot !!
> > Looking forward to your reply~
> 
> Yes, just save the attention map(B, Num, HIDDEN_SIZE), mentioned in section 4.3 of the mcan-vqa paper.

Thanks for your kindly reply !
But I failed when I load the maps extracted by myself. Here is the error:
![image](https://user-images.githubusercontent.com/73174462/104999578-0e6c2880-5a68-11eb-83f6-d9c3f57bb132.png)
  File "/home1/huangqian/zhanchenlu/mcan-vqa-master/visualization.py", line 60, in <module>
    att = att_data[attIndex_i][attIndex_j]
IndexError: list index out of range

I have tried for a long time ,but it not succeed at all.So I want to ask you if you could share the code of getting the attention maps with me which means  a lot to me. Sincerely looking forward to your reply :)

**Comment by clytze0216** [comment]
> > > Can you share the detail to get the attention maps, how can we save the 'image_attn_val.pkl' file? Thank you very much !
> > 
> > 
> > Hi,@haopan
> > Did you find the ways to get the attention maps?if you succeed ,could you share the way to me?Thanks a lot !!
> > Looking forward to your reply~
> 
> Yes, just save the attention map(B, Num, HIDDEN_SIZE), mentioned in section 4.3 of the mcan-vqa paper.

Hi,
@haoopan 
sorry for disturbing again:)
I noticed you mentioned that the size of attention maps  are (B,Num,Hiddlen_size),I'm confused. In the section 4.3,after the MLP layer, the size of the attention weight is (B, Num,1).
 the size of  (B,Num,Hiddlen_size) is the X(L),Y(L) features after the backbone ,So I want you know what should I save as the attention maps?
