### ISSUE TITLE
About the questionsForUI.pkl

### ISSUE THREAD

**Issue by clytze0216** [shahansa/mcan_attention_visualization#2]
Hello!thanks for your kindly sharing !
I want to ask where can I find the **"image_attn_val.pkl"** and the "questionsForUI.pkl", Could you share it with me ?
It means a lot to me, and if you can share it with me, I will be very grateful!
Looking forward to your reply ,thanks again!!!!

**Comment by shahansa** [comment]
Hi @clytze0216 ,

`I want to ask where can I find the "image_attn_val.pkl" and the "questionsForUI.pkl"`
>>> `image_attn_val.pkl` is the learned attention weights per region proposal extracted from the mcan-vqa model. You can find this in `section 4.3 , equation (5)` of the [paper](https://arxiv.org/pdf/1906.10770.pdf). `questionsForUI.pkl` is a subset of question ids in the val set  of VQA-v2 which I used to generate the visualization on. 

`Could you share it with me ?`
>>> Unfortunately I don't have the files with me now, but I'm sure it is straightforward to extract them yourself.

**Comment by clytze0216** [comment]
@shahansa 
Thanks for your kindly reply!
I konw what the "attention weights " mean and I  read the paper for many times .However,I am very new to this field ,My coding skills are poor, have tried many times before, but I failed all the time.

So it was with great regret that I came to ask if you could share the code for extracting attention weights and extracting questionsForui.pkl. I'm really sorry if this is a problem for you.Forgive me for my incompetence

Thanks a lot for disturbing you  again

**Comment by shahansa** [comment]
@clytze0216 I'm sorry to hear that you have tried but could not obtain the attention weights. I wish I could help you, but I no longer have the codebase with me. To hand over the said files to you, I will need to take effort to analyze and annotate the mcan-vqa code all over again. I hope you find some way to figure this out on yourself and I wish you good luck.

**Comment by clytze0216** [comment]
@shahansa 
Sorry to bother you again:)

I would like to ask you if **questionsForUI.pkl** refers to extracting the question_id from **v2_openended_mscoco_val2014_question. json**?

**Comment by shahansa** [comment]
@clytze0216 yes. these are a subset of question ids stored in a list as it is obvious from the line 
https://github.com/shahansa/mcan_attention_visualization/blob/cc225ee80346986c595a332179d47cbf443a777d/img_attn_visualization.py#L48
you can use your own format. just change the code accordingly.

**Comment by clytze0216** [comment]
I'm so sorry to disturb you again ,It's all my fault :(
I extract the attention weight ,but I met the error:

 _**File "/home1/huangqian/zhanchenlu/mcan-vqa-master/visualization.py", line 100, in <module>
    A[bbox[1]:bbox[3], bbox[0]:bbox[2], ] += att[k]
RuntimeError: The size of tensor a (552) must match the size of tensor b (100) at non-singleton dimension 1**_

the size of bbox :[0 282 552 511]
the size of att(the attention weight ):[256 100 1]

I want to ask  how could I solve the dismatch between the att[k] and the bbox?

**Here is the code I  used to save the attention weight :**
class AttFlat(nn.Module):
    def __init__(self, __C):
        super(AttFlat, self).__init__()
        self.__C = __C

        self.mlp = MLP(
            in_size=__C.HIDDEN_SIZE,
            mid_size=__C.FLAT_MLP_SIZE,
            out_size=__C.FLAT_GLIMPSES,
            dropout_r=__C.DROPOUT_R,
            use_relu=True
        )
        self.linear_merge = nn.Linear(
            __C.HIDDEN_SIZE * __C.FLAT_GLIMPSES,
            __C.FLAT_OUT_SIZE
        )

    def forward(self, x, x_mask):

   

        att = self.mlp(x)
      

        att = att.masked_fill(
            x_mask.squeeze(1).squeeze(1).unsqueeze(2),
            -1e9
        )
        att = F.softmax(att, dim=1)
        _

> att_map=att

_
        att_list = []
        for i in range(self.__C.FLAT_GLIMPSES):
            att_list.append(
                torch.sum(att[:, :, i: i + 1] * x, dim=1)
            )
        x_atted = torch.cat(att_list, dim=1)
        x_atted = self.linear_merge(x_atted)

>         return  x_atted,  att_map

Is there some errors?
I'm so sorry for taking your time!
Looking forward to your reply ,thanks a lot !

**Comment by shahansa** [comment]
@clytze0216 sorry can't debug your code for you. Please post any issues related to this repo or if you need conceptual understanding. Please refer to `numpy indexing and slicing`  manual to have a better understanding on how to add a costant to slice of a numpy array.
