### ISSUE TITLE
the size of attention weight 

### ISSUE THREAD

**Issue by clytze0216** [shahansa/mcan_attention_visualization#3]
Hi,
Thanks for your sharing!
I want you ask that : what the size of the attention  weight and the attention maps ? (BS, NUM,hidden size）or (BS,NUM,1)?

By the way, did you know how to get the Visualizations of the learned attention maps  in Figure.7 of the mcan paper？

Looking forward to your reply!thanks a lot!

**Comment by shahansa** [comment]
@clytze0216 
1. ` what the size of the attention weight and the attention maps ?`
>>> Again, this is clear from the source [paper](https://openaccess.thecvf.com/content_CVPR_2019/html/Yu_Deep_Modular_Co-Attention_Networks_for_Visual_Question_Answering_CVPR_2019_paper.html). For object attention weights,  At section 4.3, The output image features `X(L)=  [x(L)1;...;x(L)m]∈Rm×d ` where m is dynamic number of objects less than 100. To deal with the variable number of objects, m is zero padded to 100. `Equation (5)` defines α which is the learned attention weights (`m` real numbers and `100-m` 0s). So for a batch of `BS`, you should be obtaining the attention weight of dimension `(BS, 100, 1)`.  I am not sure what you mean by 'size of attention map'. I suggest you go through the paper thoroughly before asking questions here. 

2.  `did you know how to get the Visualizations of the learned attention maps in Figure.7 of the mcan paper`

>>> No didn't try that.

**Comment by ckj1221** [comment]
> 您好， 感谢您的分享！ 我想让你问：注意力权重和注意力图的大小是多少？(BS, NUM,隐藏尺寸）还是 (BS,NUM,1)？
> 
> 顺便问一下，你知道如何得到 mcan 论文图 7 中学习到的注意力图的可视化吗？
> 
> 期待您的回复！非常感谢！





Hello, has your problem been solved? I still don’t know how to get the image_attn_val.pkl file

**Comment by shahansa** [comment]
@ckj1221  I'm out of touch with the MCAN code now but i'll give some pointers which might help to obtain image attention weights per object.  Please note that this is just a hunch. I don't have the setup now to verify and reproduce the exact steps. 
Try printing the shape of att in https://github.com/MILVLG/mcan-vqa/blob/6b165e9a88800e2a09ece4645a3c8261938897c6/core/model/net.py#L43 . you need this only for images. so make the module to return the `att` and get it in https://github.com/MILVLG/mcan-vqa/blob/6b165e9a88800e2a09ece4645a3c8261938897c6/core/model/net.py#L121 . from there you can append it to an array and dump into disk (into pkl file in this case). Hope this helps.
